bacchus/bacchus/urls.py
from filebrowser.sites import site

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# rest_framework
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Machina Forum
from machina import urls as machina_urls

# Serializers define the API representation.


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    '''ViewSets define the view behavior.'''
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # filebrowser
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),

    path('admin/', admin.site.urls),

    # machina
    path('forum/', include(machina_urls)),

    # django-registration-redux
    path('accounts/', include('registration.backends.admin_approval.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # bacchus apps
    path('', include('main.urls')),
    path('pigeon/', include('pigeonapp.urls')),
    path('dove/', include('doveapp.urls')),
    path('picus/', include('picusapp.urls')),

    # todo
    path('todo/', include('todo.urls', namespace="todo")),

    # path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

    # django-private-chat
    path('chat/', include('django_private_chat.urls')),

    # wiki
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),

    # captcha
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bacchus/main/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('chat', views.chat, name='chat'),
    path('flower', views.flower_view, name='flower_view'),
    path('gene_symbol_autocomplete', views.GeneSymbolAutocomplete.as_view(), name='gene_symbol_autocomplete'),
    re_path(r'igv/(?P<track>.+)', views.igv, name='igv'),

    path('project_create', views.project_create, name='project_create'),
    path('panel_create', views.panel_create, name='panel_create'),

    path('institute/browse', views.institute_browse, name='institute_browse'),
    path('project/browse', views.project_browse, name='project_browse'),
    path('panel/browse', views.panel_browse, name='panel_browse'),
    path('panel/browse/curated', views.panel_browse_curated, name='panel_browse_curated'),

    re_path(r'^institute/(\d+)/$', views.institute_current, name='institute_current'),
    re_path(r'^project/(\d+)/$', views.project_current, name='project_current'),
    re_path(r'^panel/(\d+)/$', views.panel_current, name='panel_current'),

    re_path(r'^project/update/(\d+)/$', views.project_update, name='project_update'),
    re_path(r'^panel/update/(\d+)/$', views.panel_update, name='panel_update'),

    re_path(r'^project/delete/(\d+)/$', views.project_delete, name='project_delete'),
    re_path(r'^panel/delete/(\d+)/$', views.panel_delete, name='panel_delete'),

    path('bed_create', views.bed_create, name='bed_create'),

    path('genes_diseases', views.genes_diseases, name='genes_diseases'),
    path('genes_panels', views.genes_panels, name='genes_panels'),

    path('genes_diseases/browse', views.genes_diseases_browse, name='genes_diseases_browse'),
    path('genes_panels/browse', views.genes_panels_browse, name='genes_panels_browse'),
]

bacchus/templates/base.html
{% load i18n %}
{% load static %}


<html lang="en">
<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'main/bootstrap/css/bootstrap.min.css' %}">

  <!-- IGV CSS -->
  <link rel="stylesheet" href="{% static 'main/igv/css/igv.css' %}">

  <script type="text/javascript" src="{% static 'main/jquery/js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'main/popper/js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
  <!-- IGVjs -->
  <script type="text/javascript" src="{% static "main/igv/js/igv.min.js" %}"></script>

  <link rel="shortcut icon" href="{% static 'main/bacchus/img/favicon.png' %}"/>

  <title>{% block title %}Bacchus{% endblock %}</title>

  {% block extra_js %}{% endblock extra_js %}
</head>

<!-- django-todo-->
{% block extrahead %}{% endblock extrahead %}

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="{% url 'main:index' %}" class="brand-logo left" style="margin:8px;"><img src="{% static 'main/bacchus/css/img/genera_logo_dark.png' %}" height="48"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% include 'includes/navbaritems_left.html' %}
      {% include 'includes/navbaritems_right.html' %}
    </div>
  </nav>

  {% include 'includes/breadcrumbs.html' %}

  {% include 'includes/messaging.html' %}

  <div class="container-fluid">
    {% block content %} {% endblock %}
  </div>

  {% include 'includes/footer.html' %}
</body>
</html>

bacchus/templates/browse.html
{% extends 'base.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}


{% block content %}
<div class="row" style="margin:15px;">
	<a href="{% querystring '_export'='csv' %}">⬇Csv</a>
</div>

{% for table in tables %}
<h4>{{ table.title }}</h4>
<p style="color:#FF0000";>{{ table.note }}</p>
{% render_table table.table %}
{% endfor %}
{% endblock %}

bacchus/templates/form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<h2 align="center">{{ title|safe }}</h2>
<p align="center">{{ note|safe }}</p>
<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form %}
        {% crispy form %}
        {% elif formset %}
        {% crispy formset %}
        {% endif %}
</form>
{% endblock %}

bacchus/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<h2 align="center">{{ title }}</h2>
<p align="center">{{ note }}</p>

<div class="row">
{% for collection in data %}
<div class="col-sm-6">
  <div class="card">
    {% if collection.rows %}
    <div class="card-header">
      <h5>{{ collection.collection_title}}</h5>
    </div>
    <ul class="list-group list-group-flush">
      {% for row in collection.rows %}
        {% if row.viewer %}
          <li class="list-group-item">
            <a href="{% url row.viewer track=row.media %}">
              <img src="{% static row.icon %}" alt='👁'>
            </a>
            <a href="{{ row.media }}">{{ row.name }}</a>
          </li>
        {% elif row.link %}
          <li class="list-group-item">
            <a href="{% url row.link %}">{{ row.name }}</a>
          </li>
        {% elif row.media %}
          <li class="list-group-item">
            <a href="{{ row.media }}">{{ row.name }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endfor %}
</div>

{% endblock %}