bacchus/bacchus/urls.py
from filebrowser.sites import site

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# rest_framework
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Machina Forum
from machina import urls as machina_urls

# Serializers define the API representation.


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    '''ViewSets define the view behavior.'''
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # filebrowser
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),

    path('admin/', admin.site.urls),

    # machina
    path('forum/', include(machina_urls)),

    # django-registration-redux
    path('accounts/', include('registration.backends.admin_approval.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # bacchus apps
    path('', include('main.urls')),
    path('pigeon/', include('pigeonapp.urls')),
    path('dove/', include('doveapp.urls')),
    path('picus/', include('picusapp.urls')),

    # todo
    path('todo/', include('todo.urls', namespace="todo")),

    # path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

    # django-private-chat
    path('chat/', include('django_private_chat.urls')),

    # wiki
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),

    # captcha
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bacchus/main/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('chat', views.chat, name='chat'),
    path('flower', views.flower_view, name='flower_view'),
    path('gene_symbol_autocomplete', views.GeneSymbolAutocomplete.as_view(), name='gene_symbol_autocomplete'),
    re_path(r'igv/(?P<track>.+)', views.igv, name='igv'),

    path('project_create', views.project_create, name='project_create'),
    path('panel_create', views.panel_create, name='panel_create'),

    path('institute/browse', views.institute_browse, name='institute_browse'),
    path('project/browse', views.project_browse, name='project_browse'),
    path('panel/browse', views.panel_browse, name='panel_browse'),
    path('panel/browse/curated', views.panel_browse_curated, name='panel_browse_curated'),

    re_path(r'^institute/(\d+)/$', views.institute_current, name='institute_current'),
    re_path(r'^project/(\d+)/$', views.project_current, name='project_current'),
    re_path(r'^panel/(\d+)/$', views.panel_current, name='panel_current'),

    re_path(r'^project/update/(\d+)/$', views.project_update, name='project_update'),
    re_path(r'^panel/update/(\d+)/$', views.panel_update, name='panel_update'),

    re_path(r'^project/delete/(\d+)/$', views.project_delete, name='project_delete'),
    re_path(r'^panel/delete/(\d+)/$', views.panel_delete, name='panel_delete'),

    path('bed_create', views.bed_create, name='bed_create'),

    path('genes_diseases', views.genes_diseases, name='genes_diseases'),
    path('genes_panels', views.genes_panels, name='genes_panels'),

    path('genes_diseases/browse', views.genes_diseases_browse, name='genes_diseases_browse'),
    path('genes_panels/browse', views.genes_panels_browse, name='genes_panels_browse'),
]

bacchus/templates/includes/breadcrumbs.html
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'main:institute_browse' %}">Institute: {{ request.session.current_institute_name }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'main:project_browse' %}">Project: {{ request.session.current_project_name }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'main:panel_browse_curated' %}">Panel: {{ request.session.current_panel_name }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'pigeon:pipeline_browse_curated' %}">Sample: {{ request.session.current_pipeline_name }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'pigeon:pipeline_browse_curated' %}">Variant: {{ request.session.current_pipeline_name }}</a>
    </li>
  </ol>
</nav>

bacchus/templates/includes/footer.html
<footer class="footer">
  <div class="container text-muted">
    <div class="row">
      <div class="col">
        <h5>Bacchus</h5>
        <p>You can use rows and columns here to organize your footer content.</p>
      </div>

      <div class="col">
        <h6>Links</h6>
        <ul>
          <li>
            <a href="{% url 'wiki:root' %}">
              📚 Documentation </a>
          </li>
          <li>
            <a href="{% url 'forum:index' %}">
              🗨 Forums </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container text-muted">
    Bacchus
    <a href="http://gen-era.com.tr">Gen-Era</a>
  </div>
</footer>

bacchus/templates/includes/messaging.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endfor %}

bacchus/templates/includes/navbaritems_left.html
{% load static %}

<ul class="navbar-nav mr-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'pigeon:index' %}">
      <img src={% static 'main/bacchus/img/pigeon.png' %} height=24><h6>Pigeon</h6>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'dove:index' %}">
      <img src={% static 'main/bacchus/img/dove.png' %} height=24><h6>Dove</h6>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'picus:index' %}">
      <img src={% static 'main/bacchus/img/picus.png' %} height=24><h6>Picus</h6>
    </a>
  </li>
</ul>

bacchus/templates/includes/navbaritems_right.html
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'todo:lists' %}">
      <h6>☑ Todo</h6>
    </a></li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'todo:mine' %}">
      <h6>📜 Tasks</h6>
    </a></li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'nyt:json_get' %}">
      <h6>🔔 Notifications</h6>
    </a></li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'main:chat' %}">
      <h6>💬 Messages</h6>
    </a></li>


  {% if user.is_authenticated %}
  <li class="nav-item">
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown-user" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      ☺ {{ user.username }}
    </a>
    <div class="dropdown-menu" id="dropdown-user">
      <a class="dropdown-item" href="{% url 'admin:index' %}">⚙ Admin</a>
      <a class="dropdown-item" href="{% url 'auth_logout' %}">Log out</a>
    </div>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link"  href="{% url 'auth_login' %}">
      <h6>Log in</h6>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'registration_register' %}">
      <h6>Register</h6>
    </a>
  </li>
  {% endif %}
</ul>

bacchus/templates/includes/searchbar.html
<div class="mx-auto">
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>